### ISSUE TITLE
Questions regarding the project goal

### ISSUE THREAD

**Issue by asonsgh** [Paillat-dev/viralfactory#85]
What happens after the free OpenAI API key credits run out? And what if Anthropic isn't available in many countries, including mine? I think you should make the app fully free! Your app is very time-consuming and seems like a waste of time because:
- It has no scheduled jobs
- It requires high CPU, RAM, graphics, and electricity. I don't understand the idea behind this. Do you enjoy wasting time? 
I've seen many open projects that require minimal effort and are completely free.
Instead of wasting your time and effort, I suggest working on ShortGPT! If you need a fully free version, please let me know. By the way, I appreciate your effort!

**Comment by Paillat-dev** [comment]
Thank you for your thoughtful questions and feedback on the project. I appreciate your interest and the time you've taken to share your concerns. Let me address each of your points in detail:

1. API Availability and Costs:
   The project is designed with flexibility in mind. You can easily switch between AI providers (like Anthropic or OpenAI) with a single click. This allows users to choose based on availability and pricing in their region. Regarding API credits, using cloud-based AI services actually reduces the need for powerful local hardware. You're essentially paying for their computing power rather than using your own, which can be more cost-effective and accessible for many users.

2. Scheduled Jobs:
   You're absolutely right that scheduled jobs would be a valuable feature. Thank you for the suggestion. I opened a specific issue for this feature request so we can discuss and potentially implement it in the future. #86 

3. Resource Requirements:
   I understand your concerns about CPU, RAM, graphics, and electricity usage. Currently, the most resource-intensive components are voice generation and video editing. For voice generation, I'm planning to add Eleven Labs integration (#87 ), which will significantly reduce local GPU usage. Video editing, unfortunately, does require substantial local processing power. However, this is a common challenge in this space and not unique to this project.

4. Comparison to ShortGPT:
   I appreciate you bringing up ShortGPT. While I have contributed to that project in the past, I created this project for several important reasons:

   a) Modularity and Customization: This project aims to offer broader functionality and easier customization, allowing for faster iteration and more flexible use cases.

   b) True Open Source: Unlike ShortGPT, this project is truly open source under OSI-approved terms. Let me elaborate on why this is crucial:

      - ShortGPT's license is not a Free and Open Source Software (FOSS) license. It restricts commercial use based on organization size, creates a tiered licensing model, limits modification rights, and requires revenue sharing for larger companies.
      - These restrictions mean that contributions to ShortGPT could potentially become inaccessible to the contributors themselves if their organization grows, or if the project's direction changes.
      - The license severely limits forking rights, which is a fundamental aspect of open source collaboration.

   c) Long-term Viability: With a true open source license, this project ensures that your contributions and usage rights are protected. You can freely use, modify, and distribute the software without concerns about future commercialization or restricted access.

   d) Avoiding Commercialization Issues: I've designed this project to remain free from advertising or commercial upselling within the app itself, ensuring a clean and focused user experience. I do not want to participate to a project whoose entire goal is to advertise something I am not even a part of.

5. Project Goals:
   Viral Factory is indeed a complex project, but its aim is to provide a highly modular and customizable platform for automating social media content production. While it may seem time-consuming, the goal is to create a flexible system that can adapt to a wide variety of use cases and workflows.

I want to emphasize that I'm not wasting time or effort. This project is both a technical challenge and a genuine attempt to create a versatile, open tool for content creation. By keeping it truly open source, I'm ensuring that all contributions (including my own) remain freely available to the community, can be built upon by others, and are protected from potential future restrictions.

**I sincerely appreciate your feedback and your recognition of the effort involved. If you have any other suggestions or questions, please don't hesitate to ask. Your input is valuable in shaping the direction of this project and ensuring it meets the needs of its users.**

**Comment by asonsgh** [comment]
hmmmmmm Since i am Not a Coder But i am Working on Project That is Totally Free. This will have Alot of options for user to play and its totally free. llms that i use and image gens that i use totally free even these do not require the user presence everything run on cloud.

Free Models : gpt4free, BING, Gimini, huggingchat, and many other These are totally free.
Image models: stable diffusion laxica, leonardio, cominc fectory this will make the content very unique and less likely to be flaged. i'll get back to you soon. or if u have telegram or whatsapp please let me know if you are intrested in collaboration. i am also looking for some help here's mine wa and telegram +923080058888

**Comment by Paillat-dev** [comment]
Thank you for your follow-up and for sharing your ideas. I appreciate your enthusiasm for creating free and accessible tools. However, I need to clarify some important points about the services you've mentioned:

1. Unofficial API access:
   Services like "gpt4free" are not officially supported by the AI providers. They involve reverse-engineering or bypassing official APIs, which violates the terms of service of platforms like OpenAI, Microsoft (Bing), and Google (Gemini). Using these unofficial methods can lead to:
   - Unreliable service that may stop working at any time
   - Potential legal issues for both developers and users
   - Ethical concerns about using services without proper authorization

2. API usage vs. user interaction:
   You proposed other solutions as well. However, there's a significant difference between using a service through its official API and accessing it as a regular user. APIs are designed for programmatic access and often have different rate limits, cost structures, and terms of use. Using a service meant for human interaction in an automated way typically violates the platform's terms of service and is nor practiacal nor easy. And often, theese service do not provide a free API, they just proc

I hope this explains my position on using unofficial or unsupported services. If you have ideas for integrating legitimate free or open-source AI models that align with our project's goals and ethical standards, I'd be happy to discuss those further.

**Comment by asonsgh** [comment]
it's not only about gpt4free..
